from openai import OpenAI
api_key = "********************************************"
client = OpenAI(api_key=api_key)

response_embedding = client.embeddings.create(
    input="'Here’s the extracted text from the image:\n\n| Sr No. | Description of Supply of Goods                                                                  | Supplier of Goods                                                       | Recipient of Goods                                         |\n|--------|------------------------------------------------------------------------------------------------|------------------------------------------------------------------------|----------------------------------------------------------|\n| 1.     | Cashew nuts, not shelled or peeled                                                             | Agriculturist                                                          | Any registered person                                      |\n| 2.     | Bidi wrapper leaves (tendu)                                                                    | Agriculturist                                                          | Any registered person                                      |\n| 3.     | Tobacco leaves                                                                                 | Agriculturist                                                          | Any registered person                                      |\n| 4.     | Silk yarn                                                                                      | Any person who manufactures silk yarn from raw silk or silk worm cocoons for supply of Silk Yarn | Any registered person                                      |\n| 5.     | Raw cotton                                                                                     | Agriculturist                                                          | Any registered person                                      |\n| 6.     | Supply of lottery                                                                               | State Government, Union Territory or any local authority               | Lottery distributor or selling agent                      |\n| 7.     | Used vehicles, seized and confiscated goods, old and used goods, waste and scrap               | Central Government, State Government, Union territory or a local authority | Any registered person                                      |'",
    model="text-embedding-3-small"
)

print(response_embedding.data[0].embedding)